apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}
        imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
        env:
        - name: DB_HOST
          value: {{ .Release.Name }}-postgres
        - name: DB_NAME
          value: {{ .Values.postgres.database }}
        - name: DB_USER
          value: {{ .Values.postgres.username }}
        - name: DB_PASS
          value: {{ .Values.postgres.password }}
        ports:
        - containerPort: 5000