apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  type: {{ .Values.services.backend.type }}
  ports:
  - port: {{ .Values.services.backend.port }}
    targetPort: {{ .Values.services.backend.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-backend