{{- if .Values.postgres.initScript.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.initScript.configMapName }}
data:
  init.sql: |
    -- You'll need to replace this with your actual initialization SQL
    -- This is just a placeholder
    CREATE TABLE IF NOT EXISTS sample_table (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL
    );
{{- end }}
