apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  type: {{ .Values.services.postgres.type }}
  ports:
  - port: {{ .Values.services.postgres.port }}
    targetPort: {{ .Values.services.postgres.targetPort }}
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Release.Name }}-postgres

